package com.play.golf.perf.tracker.data.repository

import androidx.paging.Pager
import androidx.paging.PagingConfig
import androidx.paging.PagingData
import androidx.paging.map
import com.play.golf.perf.tracker.core.common.Resource
import com.play.golf.perf.tracker.core.common.ResourceFlow
import com.play.golf.perf.tracker.data.local.dao.PlayerDao
import com.play.golf.perf.tracker.data.local.dao.ShotDao
import com.play.golf.perf.tracker.data.mapper.toDomain
import com.play.golf.perf.tracker.data.mapper.toEntity
import com.play.golf.perf.tracker.data.remote.api.GolfApiService
import com.play.golf.perf.tracker.domain.model.Player
import com.play.golf.perf.tracker.domain.model.PlayerDetail
import com.play.golf.perf.tracker.domain.model.Shot
import com.play.golf.perf.tracker.domain.repository.GolfRepository
import kotlinx.coroutines.flow.Flow
import kotlinx.coroutines.flow.flow
import kotlinx.coroutines.flow.map
import timber.log.Timber
import javax.inject.Inject
import javax.inject.Singleton

@Singleton
class GolfRepositoryImpl @Inject constructor(
    private val apiService: GolfApiService,
    private val playerDao: PlayerDao,
    private val shotDao: ShotDao,
) : GolfRepository {

    companion object {
        private const val PAGE_SIZE = 10
        private const val PREFETCH_DISTANCE = 5
        const val REQUEST_DESCRIPTION_PLAYERS = "fetch player list"
        const val REQUEST_DESCRIPTION_PLAYER_DETAIL = "fetch player detail"
    }

    // Player List

    /**
     * Returns a paged flow of [Player] domain models.
     * Room is the single source of truth — Paging 3 reads directly from
     * [PagingSource] generated by the DAO query.
     *
     * When both [nameQuery] and [clubFilter] are empty, all players are returned.
     * Search and filter happen locally against the Room cache — no API call.
     */
    override fun getPagedPlayers(
        nameQuery: String,
        clubFilter: String
    ): Flow<PagingData<Player>> {
        Timber.d("GolfRepository: getPagedPlayers — query='$nameQuery' club='$clubFilter'")

        return Pager(
            config = PagingConfig(
                pageSize         = PAGE_SIZE,
                prefetchDistance = PREFETCH_DISTANCE,
                enablePlaceholders = false
            ),
            pagingSourceFactory = {
                if (nameQuery.isEmpty() && clubFilter.isEmpty()) {
                    playerDao.getPagedPlayers()
                } else {
                    playerDao.searchPagedPlayers(
                        nameQuery  = nameQuery,
                        clubFilter = clubFilter
                    )
                }
            }
        ).flow.map { pagingData ->
            pagingData.map { entity -> entity.toDomain() }
        }
    }

    /**
     * Fetches all players from the remote API and refreshes the Room cache.
     * Called on app start and when the network reconnects.
     *
     * Strategy:
     *  1. Emit [Resource.Loading]
     *  2. Fetch from API with exponential retry (via [ResourceFlow])
     *  3. On success: clear stale cache → insert fresh data → emit [Resource.Success]
     *  4. On error: emit [Resource.Error] — existing cache remains intact for offline use
     */
    override fun refreshPlayers(): Flow<Resource<Unit>> = flow {
        emit(Resource.Loading())

        ResourceFlow.dispatchWithRetry(
            requestAction       = { apiService.getPlayers() },
            requestDescription  = REQUEST_DESCRIPTION_PLAYERS,
            retryCount          = 2
        ).collect { resource ->
            when (resource) {
                is Resource.Loading -> { /* already emitted above */ }

                is Resource.Success -> {
                    val players = resource.data?.data.orEmpty()
                    Timber.d("GolfRepository: refreshPlayers — received ${players.size} players")

                    // Atomic cache refresh — clear then insert
                    playerDao.clearPlayers()
                    playerDao.insertPlayers(players.map { it.toEntity() })

                    Timber.d("GolfRepository: refreshPlayers — cache updated successfully")
                    emit(Resource.Success(Unit))
                }

                is Resource.Error -> {
                    Timber.w("GolfRepository: refreshPlayers failed — ${resource.message}")
                    emit(
                        Resource.Error(
                            message             = resource.message ?: "Failed to fetch players",
                            isConnectivityError = resource.isConnectivityError
                        )
                    )
                }
            }
        }
    }

    override suspend fun getDistinctClubs(): List<String> =
        playerDao.getDistinctClubs()

    // Player Detail

    /**
     * Offline-first player detail fetch.
     *
     * Strategy:
     *  1. Check Room cache for existing detail
     *  2. If cache hit and [forceRefresh] is false → serve immediately from cache
     *  3. Always attempt a background network fetch to keep data fresh
     *  4. On network success → update cache → re-emit from cache
     *  5. On network failure with no cache → emit [Resource.Error]
     */
    override fun getPlayerDetail(
        playerId: Int,
        forceRefresh: Boolean
    ): Flow<Resource<PlayerDetail>> = flow {
        emit(Resource.Loading())

        // Step 1 — try cache first
        val cachedDetail  = playerDao.getPlayerDetail(playerId)
        val cachedShots   = shotDao.getShotsForPlayer(playerId)

        if (cachedDetail != null && !forceRefresh) {
            Timber.d("GolfRepository: serving player $playerId from cache")
            emit(
                Resource.Success(
                    cachedDetail.toDomain(cachedShots.map { it.toDomain() })
                )
            )
        }

        // Step 2 — fetch from network to refresh cache
        Timber.d("GolfRepository: fetching player $playerId from network")
        ResourceFlow.dispatchWithRetry(
            requestAction      = { apiService.getPlayerDetail(playerId) },
            requestDescription = "$REQUEST_DESCRIPTION_PLAYER_DETAIL (id=$playerId)",
            retryCount         = 2
        ).collect { resource ->
            when (resource) {
                is Resource.Loading -> { /* loading already emitted */ }

                is Resource.Success -> {
                    val dto = resource.data?.data
                    if (dto == null) {
                        Timber.w("GolfRepository: player detail $playerId response body was null")
                        if (cachedDetail == null) {
                            emit(Resource.Error("Player data unavailable"))
                        }
                        return@collect
                    }

                    // Atomically update cache — clear shots first, then insert detail + shots
                    shotDao.clearShotsForPlayer(playerId)
                    playerDao.insertPlayerDetailWithShots(
                        playerDetail = dto.toEntity(),
                        insertShots  = {
                            shotDao.insertShots(dto.shots.map { it.toEntity(playerId) })
                        }
                    )

                    // Re-read from cache to emit the canonical domain model
                    val freshDetail = playerDao.getPlayerDetail(playerId)
                    val freshShots  = shotDao.getShotsForPlayer(playerId)

                    if (freshDetail != null) {
                        Timber.d("GolfRepository: player $playerId cache updated, emitting fresh data")
                        emit(
                            Resource.Success(
                                freshDetail.toDomain(freshShots.map { it.toDomain() })
                            )
                        )
                    }
                }

                is Resource.Error -> {
                    Timber.w("GolfRepository: player detail $playerId fetch failed — ${resource.message}")
                    // Only emit error if we had nothing from cache
                    if (cachedDetail == null) {
                        emit(
                            Resource.Error(
                                message             = resource.message ?: "Failed to fetch player detail",
                                isConnectivityError = resource.isConnectivityError
                            )
                        )
                    }
                }
            }
        }
    }

    // Shot

    override suspend fun getCachedShot(playerId: Int, shotId: Int): Shot? {
        return shotDao.getShot(playerId, shotId)?.toDomain()
    }
}